# Generated by Django 6.1 on 2026-08-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='interests_hobbies',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='what_i_love_about_job',
            field=models.TextField(blank=True),
        ),
    ]
