# Generated by Django 6.1 on 2026-08-22 06:46

import apps.company.models
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/')),
                ('prefix', models.CharField(default='DF', help_text='Login ID generation prefix', max_length=5)),
                ('timezone', models.CharField(default='Asia/Kolkata', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_weekdays', models.JSONField(default=apps.company.models.default_working_weekdays)),
                ('standard_hours_per_day', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=4)),
                ('half_day_threshold_hours', models.DecimalField(decimal_places=2, default=Decimal('8'), max_digits=4)),
                ('break_time_hrs', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=4)),
                ('sick_leave_backdate_days', models.PositiveIntegerField(default=30)),
                ('paid_leave_total', models.PositiveIntegerField(default=24)),
                ('sick_leave_total', models.PositiveIntegerField(default=7)),
                ('pf_rate_percent', models.DecimalField(decimal_places=2, default=Decimal('12'), max_digits=5)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=Decimal('200'), max_digits=10)),
                ('salary_components', models.JSONField(default=apps.company.models.default_salary_components)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('date', models.DateField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_holidays', to='company.company')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('company', 'date')},
            },
        ),
    ]
