# Generated by Django 6.1 on 2026-08-22 07:48

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyconfig',
            name='half_day_threshold_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('4'), max_digits=4),
        ),
    ]
