# Generated by Django 6.1 on 2026-08-22 08:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('wage_type', models.CharField(default='fixed', max_length=10)),
                ('monthly_wage', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yearly_wage', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('working_days_per_week', models.PositiveSmallIntegerField(default=5)),
                ('break_time_hrs', models.DecimalField(decimal_places=2, default=Decimal('1'), max_digits=4)),
                ('basic', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('standard_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('performance_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('lta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('fixed_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pf_employee', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pf_employer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=Decimal('200'), max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salary_structure', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.PositiveSmallIntegerField()),
                ('year', models.PositiveIntegerField()),
                ('working_days', models.PositiveSmallIntegerField(default=0)),
                ('payable_days', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('basic', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('hra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('standard_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('performance_bonus', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('lta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('fixed_allowance', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gross_earnings', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('pf_deduction', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('professional_tax', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('generated', 'Generated'), ('sent', 'Sent')], default='draft', max_length=10)),
                ('flags', models.JSONField(blank=True, default=dict)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='payslips/%Y/%m/')),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to=settings.AUTH_USER_MODEL)),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_payslips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-year', '-month'],
                'unique_together': {('employee', 'month', 'year')},
            },
        ),
    ]
