# Generated by Django 6.1 on 2026-08-22 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='linked_time_off',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='leaves.timeoffrequest'),
        ),
    ]
